name: lockin_app
description: A motivational quote and journaling app built with Flutter.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & State
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_colorpicker: ^1.1.0

  # Firebase Packages (latest stable versions)
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  #secure local storage for Remember Me
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/quotes.json
    - assets/icons/icon.png
    - assets/splash/splash_icon.png

# --------------------------------
# App Icon Configuration
# --------------------------------
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/icon.png"
  min_sdk_android: 21

# --------------------------------
# Splash Screen Configuration
# --------------------------------
flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/splash_icon.png
  android: true
  ios: true
  web: true
  android_12:
    image: assets/splash/splash_icon.png
    color: "#ffffff"
